from sys import exc_info
from fastapi import APIRouter, Depends, HTTPException, status, Request
from sqlalchemy.orm import Session

from common.api_models.tag_model import TagData
from common.api_models.pellet_model import (
    PelletCreate,
    PelletData,
)

from common.database_models.pellet_model import (
    PelletDB,
)

from backend.services.processing_service import (
    processing_service,
    ProcessingServiceError,
)

from common.exceptions.quota_exceptions import QuotaInsufficientException

from pydantic import BaseModel
import logging

logger = logging.getLogger(__name__)


class PelletCreateRequest(BaseModel):
    title: str | None = None  # Optional, will be generated by AI
    content: str
    material_ids: list[str] | None = None
    processing_job_ids: list[str] | None = None


class BatchPelletCreateRequest(BaseModel):
    material_ids: list[str]  # Required: list of material IDs to process


class BatchPelletCreateResponse(BaseModel):
    job_id: str
    status: str
    message: str
    material_count: int


class PelletListResponse(BaseModel):
    pellets: list[PelletData]
    pagination: dict


from backend.services.pellet_service import pellet_service
from backend.services.material_service import material_service

from backend.middleware.auth import get_current_user, get_current_user_optional
from database import get_database

router = APIRouter()


def convert_pellet_to_response(pellet: PelletDB) -> PelletData:
    """Convert PelletDB to PelletResponse format"""
    view_count = 0
    if pellet.counters:
        view_count = pellet.counters.view_count

    tags = [TagData.model_validate(tag) for tag in pellet.tags]
    is_gold = any(tag.name == "gold" for tag in tags)

    pellet_data = PelletData.model_validate(pellet)
    pellet_data.tags = tags
    pellet_data.view_count = view_count
    pellet_data.is_gold = is_gold

    return pellet_data


@router.get("/", response_model=PelletListResponse)
async def get_pellets(
    limit: int | None = 10,
    sortBy: str | None = "createdAt",
    sortOrder: str | None = "desc",
    db: Session = Depends(get_database),
    current_user: dict = Depends(get_current_user),
):
    """Get pellets list for current user"""
    try:
        pellets = pellet_service.get_pellets_by_user(
            db,
            current_user["user_id"],
            limit=limit,
            sort_by=sortBy,
            sort_order=sortOrder,
        )
        converted_pellets = [convert_pellet_to_response(pellet) for pellet in pellets]
        return PelletListResponse(
            pellets=converted_pellets,
            pagination={"limit": limit, "offset": 0, "total": len(converted_pellets)},
        )
    except ValueError as e:
        logger.error("failed get_pellets_by_user, ", exc_info=e)
        raise HTTPException(status_code=400, detail=str(e))


@router.get("/public", response_model=PelletListResponse)
async def get_public_pellets(
    limit: int | None = 10,
    sortBy: str | None = "createdAt",
    sortOrder: str | None = "desc",
    db: Session = Depends(get_database),
):
    """Get public pellets without authentication"""
    try:
        pellets = pellet_service.get_public_pellets(
            db, limit=limit, sort_by=sortBy, sort_order=sortOrder
        )
        converted_pellets = [convert_pellet_to_response(pellet) for pellet in pellets]
        return PelletListResponse(
            pellets=converted_pellets,
            pagination={"limit": limit, "offset": 0, "total": len(converted_pellets)},
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.get("/{pellet_id}", response_model=PelletData)
async def get_pellet(
    request: Request,
    pellet_id: str,
    db: Session = Depends(get_database),
):
    """Get pellet by ID - supports both authenticated and anonymous access"""
    try:
        pellet = pellet_service.get_pellet_by_id(db, pellet_id)
        if pellet is None:
            raise HTTPException(status_code=404, detail="Pellet not found")

        # Get optional user info
        current_user = get_current_user_optional(request)

        # Check access permissions
        if pellet.visibility == "private":
            # Private pellets require authentication and ownership
            if current_user is None:
                raise HTTPException(
                    status_code=401,
                    detail="Authentication required to access private pellet",
                )
            if pellet.user_id != current_user["user_id"]:
                raise HTTPException(status_code=403, detail="Access denied")
        # Public pellets can be accessed by anyone

        return convert_pellet_to_response(pellet)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.put("/{pellet_id}/gold", response_model=PelletData)
async def mark_pellet_as_gold(
    pellet_id: str,
    db: Session = Depends(get_database),
    current_user: dict = Depends(get_current_user),
):
    """Mark pellet as gold (金丹)"""
    try:
        pellet = pellet_service.get_pellet_by_id(db, pellet_id)
        if pellet is None:
            raise HTTPException(status_code=404, detail="Pellet not found")

        # Check if user owns the pellet
        if pellet.user_id != current_user["user_id"]:
            raise HTTPException(status_code=403, detail="Access denied")

        # Mark pellet as gold
        updated_pellet = pellet_service.mark_as_gold(db, pellet_id)
        return convert_pellet_to_response(updated_pellet)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


class PelletVisibilityRequest(BaseModel):
    visibility: str  # "public" or "private"


@router.put("/{pellet_id}/visibility", response_model=PelletData)
async def update_pellet_visibility(
    pellet_id: str,
    request_data: PelletVisibilityRequest,
    db: Session = Depends(get_database),
    current_user: dict = Depends(get_current_user),
):
    """Update pellet visibility (public/private)"""
    try:
        if request_data.visibility not in ["public", "private"]:
            raise HTTPException(
                status_code=400, detail="Visibility must be 'public' or 'private'"
            )

        pellet = pellet_service.get_pellet_by_id(db, pellet_id)
        if pellet is None:
            raise HTTPException(status_code=404, detail="Pellet not found")

        # Check if user owns the pellet
        if pellet.user_id != current_user["user_id"]:
            raise HTTPException(status_code=403, detail="Access denied")

        # Update pellet visibility
        updated_pellet = pellet_service.update_pellet_visibility(
            db, pellet_id, request_data.visibility
        )
        return convert_pellet_to_response(updated_pellet)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.post(
    "/batch-create",
    response_model=BatchPelletCreateResponse,
    status_code=status.HTTP_202_ACCEPTED,
)
async def create_pellets_batch(
    request: BatchPelletCreateRequest,
    db: Session = Depends(get_database),
    current_user: dict = Depends(get_current_user),
):
    """Create multiple pellets from materials using AI analysis (M materials -> N pellets)"""
    import os

    try:
        # Validate that user owns all materials
        materials = []
        for material_id in request.material_ids:
            material = material_service.get_material_by_id(db, material_id)
            if material is None:
                raise HTTPException(
                    status_code=404, detail=f"Material {material_id} not found"
                )
            if material.user_id != current_user["user_id"]:
                raise HTTPException(status_code=403, detail="Access denied to material")
            materials.append(material)

        if not materials:
            raise HTTPException(status_code=400, detail="No valid materials provided")

        # Prepare materials data for Process service
        materials_info = [
            {
                "id": m.id,
                "content_type": m.content_type,
                "file_path": m.file_path,
                "file_size": m.file_size,
            }
            for m in materials
        ]

        # Call Process service to initiate pellet generation
        token = current_user.get("token")
        result = await processing_service.create_pellet_generation_job(
            materials_info=materials_info, user_id=current_user["user_id"], token=token
        )

        return BatchPelletCreateResponse(
            job_id=result["job_id"],
            status=result["status"],
            message=f"AI炼丹师正在分析 {len(materials)} 种材料，将智能生成0-N个丹药",
            material_count=len(materials),
        )

    except ProcessingServiceError as e:
        logger.error(f"Process service error: {str(e)}", exc_info=True)
        raise HTTPException(status_code=503, detail=str(e))
    except QuotaInsufficientException as e:
        logger.error(f"Insufficient credits error: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=402,
            detail={
                "error": "Insufficient credits for processing materials",
                "error_code": "QUOTA_INSUFFICIENT",
                "required_credits": e.required_amount,
                "available_credits": e.available_amount,
                "shortage": e.required_amount - e.available_amount,
                "material_count": len(request.material_ids)
            }
        )
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
