from pydantic import BaseModel, ConfigDict, field_validator
from typing import Optional, List, Dict, Any
from datetime import datetime
import json
from .tag_model import TagData

from common.database_models.pellet_model import PelletDB


class PelletCreate(BaseModel):
    title: Optional[str] = None  # Optional, will be generated by AI
    content: str
    status: str = "in-queue"  # Changed from draft to in-queue

    ai_score: Optional[float] = None  # AI-generated quality score (0-100)
    pellet_type: Optional[str] = None  # high_value, standard, specialized
    generation_metadata: Optional[Dict[str, Any]] = None
    visibility: str = "private"  # public or private
    user_id: str
    material_ids: Optional[List[str]] = None
    tag_ids: List[str] = []


class PelletData(BaseModel):
    id: str
    user_id: str
    material_ids: Optional[List[str]] = None
    title: Optional[str] = None  # Optional, will be generated by AI
    content: str
    status: str = "in-queue"  # Changed from draft to in-queue

    ai_score: Optional[float] = None  # AI-generated quality score (0-100)
    pellet_type: Optional[str] = None  # high_value, standard, specialized
    visibility: str = "private"  # public or private

    # Database store metadata as str, so we need @field_validator
    generation_metadata: Optional[Dict[str, Any]] = None

    is_gold: bool = False
    view_count: int = 0

    tags: List[TagData] = []
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)

    @field_validator("generation_metadata", mode="before")
    @classmethod
    def parse_generation_metadata(cls, v: str | dict[str, Any]):
        if isinstance(v, str):
            try:
                return json.loads(v) if v else None
            except json.JSONDecodeError:
                return None
        return v


# New model for batch pellet creation from processing
class BatchPelletData(BaseModel):
    title: str
    content: str
    material_ids: List[str] = []  # TODO
    status: str = "completed"
    tags: Optional[List[Dict[str, Any]]] = []  # TODO
    score: Optional[float] = None  # TODO
    pellet_type: Optional[str] = "standard"


class BatchPelletCreateFromProcessingRequest(BaseModel):
    user_id: str
    pellets: List[BatchPelletData]


class BatchPelletCreateFromProcessingResponse(BaseModel):
    success: bool
    created_count: int
    pellet_ids: List[str]
    message: str


class PelletResponse(BaseModel):
    success: bool
    pellet: Optional[PelletData] = None
    message: str
