import { apiRequest } from './api';
import { TagType } from '../types/tag';
import { parseIds } from '../lib/utils';

export interface Pellet {
  id: string;
  userId: string;   // camelCase alias (may not be present)
  user_id?: string; // actual field from backend (snake_case)
  title: string;
  content: string;
  tags: TagType[];
  visibility: 'public' | 'private';
  materialIds?: string[];
  processingJobIds?: string[];
  createdAt: string;
  updatedAt: string;
}


export interface PelletCounters {
  pelletId: string;
  viewCount: number;
  likeCount: number;
  estimatedReadTime: number;  // in minutes
  referencedMaterialCount: number;
  referencedJobCount: number;
  referencedPelletCount: number;
  referencedByPelletCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface PelletCreateRequest {
  title?: string;  // Optional, will be generated by AI
  content: string;
  materialIds?: string[];
  processingJobIds?: string[];
}

export interface PelletUpdateRequest {
  title?: string;
  content?: string;
}

export interface BatchPelletCreateRequest {
  material_ids: string[];  // Required: list of material IDs to process
}

export interface BatchPelletCreateResponse {
  job_id: string;
  status: string;
  message: string;
  material_count: number;
}

export interface JobStatusResponse {
  job_id: string;
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
  created_at: string;
  updated_at: string;
  pellets?: Pellet[];  // Available when status is 'completed'
}

export interface PelletListResponse {
  pellets: Pellet[];
  pagination: {
    limit: number;
    offset: number;
    total: number;
  };
}

export const pelletService = {
  // Get all pellets for current user
  getPellets: async (params?: {
    limit?: number;
    offset?: number;
    onlyGold?: boolean;
    sortBy?: 'createdAt' | 'viewCount';
    sortOrder?: 'asc' | 'desc';
  }) => {
    const queryParams = new URLSearchParams();
    if (params?.limit) queryParams.append('limit', params.limit.toString());
    if (params?.offset) queryParams.append('offset', params.offset.toString());
    if (params?.onlyGold) queryParams.append('onlyGold', params.onlyGold.toString());
    if (params?.sortBy) queryParams.append('sortBy', params.sortBy);
    if (params?.sortOrder) queryParams.append('sortOrder', params.sortOrder);

    const endpoint = `/pellets${queryParams.toString() ? `?${queryParams.toString()}` : ''}`;
    const response = await apiRequest<PelletListResponse>(endpoint, {
      method: 'GET',
    });

    // Convert comma-separated strings to arrays
    if (response.success && response.data) {
      response.data.pellets = response.data.pellets.map(pellet => ({
        ...pellet,
        materialIds: parseIds(pellet.materialIds as any),
        processingJobIds: parseIds(pellet.processingJobIds as any)
      }));
    }

    return response;
  },

  // Get pellet by ID
  getPellet: async (pelletId: string) => {
    const response = await apiRequest<Pellet>(`/pellets/${pelletId}`, {
      method: 'GET',
    });

    // Convert comma-separated strings to arrays
    if (response.success && response.data) {
      response.data = {
        ...response.data,
        materialIds: parseIds(response.data.materialIds as any),
        processingJobIds: parseIds(response.data.processingJobIds as any)
      };
    }

    return response;
  },

  // Create new pellet
  createPellet: async (data: PelletCreateRequest) => {
    const requestBody: any = {
      content: data.content,
      material_ids: data.materialIds,
      processing_job_ids: data.processingJobIds
    };
    
    // Only include title if provided
    if (data.title) {
      requestBody.title = data.title;
    }
    
    const response = await apiRequest<Pellet>('/pellets', {
      method: 'POST',
      body: JSON.stringify(requestBody),
    });

    // Convert comma-separated strings to arrays
    if (response.success && response.data) {
      response.data = {
        ...response.data,
        materialIds: parseIds(response.data.materialIds as any),
        processingJobIds: parseIds(response.data.processingJobIds as any)
      };
    }

    return response;
  },

  // Update existing pellet
  updatePellet: async (pelletId: string, data: PelletUpdateRequest) => {
    const response = await apiRequest<Pellet>(`/pellets/${pelletId}`, {
      method: 'PUT',
      body: JSON.stringify(data),
    });

    // Convert comma-separated strings to arrays
    if (response.success && response.data) {
      response.data = {
        ...response.data,
        materialIds: parseIds(response.data.materialIds as any),
        processingJobIds: parseIds(response.data.processingJobIds as any)
      };
    }

    return response;
  },

  // Get pellets generated from specific materials
  getPelletsByMaterials: async (materialIds: string[]) => {
    const idsParam = materialIds.join(',');
    const response = await apiRequest<{ pellets: Pellet[] }>(`/materials/${idsParam}/pellets`, {
      method: 'GET',
    });

    // Convert comma-separated strings to arrays
    if (response.success && response.data) {
      response.data.pellets = response.data.pellets.map(pellet => ({
        ...pellet,
        materialIds: parseIds(pellet.materialIds as any),
        processingJobIds: parseIds(pellet.processingJobIds as any)
      }));
    }

    return response;
  },

  // Get public pellets (no authentication required)
  getPublicPellets: async (params?: {
    limit?: number;
    offset?: number;
    sortBy?: 'createdAt' | 'viewCount';
    sortOrder?: 'asc' | 'desc';
  }) => {
    const queryParams = new URLSearchParams();
    if (params?.limit) queryParams.append('limit', params.limit.toString());
    if (params?.offset) queryParams.append('offset', params.offset.toString());
    if (params?.sortBy) queryParams.append('sortBy', params.sortBy);
    if (params?.sortOrder) queryParams.append('sortOrder', params.sortOrder);

    const endpoint = `/pellets/public${queryParams.toString() ? `?${queryParams.toString()}` : ''}`;
    const response = await apiRequest<PelletListResponse>(endpoint, {
      method: 'GET',
    }, false); // No authentication required for public pellets

    // Convert comma-separated strings to arrays
    if (response.success && response.data) {
      response.data.pellets = response.data.pellets.map(pellet => ({
        ...pellet,
        materialIds: parseIds(pellet.materialIds as any),
        processingJobIds: parseIds(pellet.processingJobIds as any)
      }));
    }

    return response;
  },

  // Create multiple pellets from materials using AI analysis (M materials -> N pellets)
  createPelletsFromMaterials: async (materialIds: string[]) => {
    const response = await apiRequest<BatchPelletCreateResponse>('/pellets/batch-create', {
      method: 'POST',
      body: JSON.stringify({
        material_ids: materialIds
      }),
    });

    return response;
  },

  // Get job status for batch pellet creation
  getJobStatus: async (jobId: string) => {
    const response = await apiRequest<JobStatusResponse>(`/processing/job/${jobId}`, {
      method: 'GET',
    });

    // Convert comma-separated strings to arrays for pellets if available
    if (response.success && response.data && response.data.pellets) {
      response.data.pellets = response.data.pellets.map(pellet => ({
        ...pellet,
        materialIds: parseIds(pellet.materialIds as any),
        processingJobIds: parseIds(pellet.processingJobIds as any)
      }));
    }

    return response;
  },

  // Update pellet visibility
  updateVisibility: async (pelletId: string, visibility: 'public' | 'private') => {
    const response = await apiRequest<Pellet>(`/pellets/${pelletId}/visibility`, {
      method: 'PUT',
      body: JSON.stringify({ visibility }),
    });

    // Convert comma-separated strings to arrays
    if (response.success && response.data) {
      response.data = {
        ...response.data,
        materialIds: parseIds(response.data.materialIds as any),
        processingJobIds: parseIds(response.data.processingJobIds as any)
      };
    }

    return response;
  },
};
