/var/log/danloo/*.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    copytruncate
    create 0644 danloo danloo
    sharedscripts
    postrotate
        systemctl reload rsyslog
    endscript
}